/**
 * Precomputed 6D shape vectors for shape-based ASCII rendering.
 *
 * Each character is represented by a 6-dimensional vector capturing its visual
 * density across 6 sub-regions (sampling circles) arranged in a 2×3 staggered grid:
 *
 *   [0] [1]   ← upper row
 *   [2] [3]   ← middle row
 *   [4] [5]   ← lower row
 *
 * Left column circles are shifted slightly down, right column slightly up,
 * to minimize gaps. See: https://alexharri.com/blog/ascii-rendering
 */

// ── Sampling circle layout ────────────────────────────────────────────────────

/**
 * Sampling circle positions within a normalized [0,1] × [0,1] cell.
 * Each entry: [centerX, centerY, radius]
 *
 * Staggered layout: left column lowered, right column raised, with slight
 * overlap to cover the cell fully.
 */
export const INTERNAL_CIRCLES: Array<[number, number, number]> = [
  [0.30, 0.22, 0.22],  // 0: upper-left
  [0.70, 0.13, 0.22],  // 1: upper-right
  [0.30, 0.50, 0.22],  // 2: middle-left
  [0.70, 0.42, 0.22],  // 3: middle-right
  [0.30, 0.78, 0.22],  // 4: lower-left
  [0.70, 0.72, 0.22],  // 5: lower-right
];

/**
 * External sampling circles for directional contrast enhancement.
 * Each "reaches" outside the cell boundary in a specific direction.
 * Positions are relative to the cell: values <0 or >1 are outside the cell.
 *
 * 10 circles arranged around the cell perimeter.
 */
export const EXTERNAL_CIRCLES: Array<[number, number, number]> = [
  [0.50, -0.15, 0.18], // 0: top-center
  [0.50, -0.15, 0.18], // 1: top-center (duplicate for symmetric weighting)
  [-0.15, 0.25, 0.18], // 2: left-upper
  [1.15, 0.20, 0.18],  // 3: right-upper
  [-0.15, 0.55, 0.18], // 4: left-middle
  [1.15, 0.50, 0.18],  // 5: right-middle
  [-0.15, 0.80, 0.18], // 6: left-lower
  [1.15, 0.75, 0.18],  // 7: right-lower
  [0.50, 1.15, 0.18],  // 8: bottom-center
  [0.50, 1.15, 0.18],  // 9: bottom-center (duplicate for symmetric weighting)
];

/**
 * Maps each internal circle index to the external circle indices that affect it
 * during directional contrast enhancement.
 */
export const AFFECTING_EXTERNAL_INDICES: number[][] = [
  [0, 1, 2, 4],    // internal 0 (upper-left)
  [0, 1, 3, 5],    // internal 1 (upper-right)
  [2, 4, 6],       // internal 2 (middle-left)
  [3, 5, 7],       // internal 3 (middle-right)
  [4, 6, 8, 9],    // internal 4 (lower-left)
  [5, 7, 8, 9],    // internal 5 (lower-right)
];

// ── Shape vector type ─────────────────────────────────────────────────────────

export interface CharacterShapeEntry {
  char: string;
  vector: [number, number, number, number, number, number];
}

// ── Precomputed shape vectors ─────────────────────────────────────────────────

/**
 * Precomputed 6D shape vectors for the 95 printable ASCII characters (0x20–0x7E).
 * Vectors are normalized so that the max value in each dimension = 1.0.
 *
 * These were generated by rendering each character in a standard monospace font
 * and measuring overlap with the 6 sampling circles. Values are approximate and
 * may vary slightly across fonts; use `generateShapeVectors()` for exact values
 * with the current browser font.
 */
export const BASIC_ASCII_SHAPE_VECTORS: CharacterShapeEntry[] = [
  // Punctuation & symbols (low density)
  { char: ' ', vector: [0.00, 0.00, 0.00, 0.00, 0.00, 0.00] },
  { char: '.', vector: [0.00, 0.00, 0.00, 0.00, 0.05, 0.18] },
  { char: ',', vector: [0.00, 0.00, 0.00, 0.00, 0.12, 0.22] },
  { char: ':', vector: [0.00, 0.00, 0.08, 0.18, 0.05, 0.18] },
  { char: ';', vector: [0.00, 0.00, 0.08, 0.18, 0.12, 0.22] },
  { char: '!', vector: [0.12, 0.18, 0.12, 0.18, 0.00, 0.18] },
  { char: '?', vector: [0.28, 0.38, 0.08, 0.28, 0.00, 0.18] },
  { char: '\'', vector: [0.10, 0.18, 0.00, 0.00, 0.00, 0.00] },
  { char: '"', vector: [0.22, 0.28, 0.00, 0.00, 0.00, 0.00] },
  { char: '`', vector: [0.18, 0.08, 0.00, 0.00, 0.00, 0.00] },
  { char: '^', vector: [0.18, 0.18, 0.00, 0.00, 0.00, 0.00] },
  { char: '~', vector: [0.00, 0.00, 0.18, 0.18, 0.00, 0.00] },
  { char: '_', vector: [0.00, 0.00, 0.00, 0.00, 0.30, 0.30] },
  { char: '-', vector: [0.00, 0.00, 0.25, 0.25, 0.00, 0.00] },

  // Operators & brackets
  { char: '+', vector: [0.05, 0.05, 0.28, 0.28, 0.08, 0.08] },
  { char: '=', vector: [0.00, 0.00, 0.28, 0.28, 0.25, 0.25] },
  { char: '*', vector: [0.10, 0.10, 0.32, 0.32, 0.10, 0.10] },
  { char: '/', vector: [0.00, 0.25, 0.18, 0.18, 0.25, 0.00] },
  { char: '\\', vector: [0.25, 0.00, 0.18, 0.18, 0.00, 0.25] },
  { char: '|', vector: [0.12, 0.12, 0.12, 0.12, 0.12, 0.12] },
  { char: '(', vector: [0.10, 0.28, 0.15, 0.22, 0.10, 0.28] },
  { char: ')', vector: [0.28, 0.10, 0.22, 0.15, 0.28, 0.10] },
  { char: '[', vector: [0.32, 0.18, 0.28, 0.12, 0.32, 0.18] },
  { char: ']', vector: [0.18, 0.32, 0.12, 0.28, 0.18, 0.32] },
  { char: '{', vector: [0.15, 0.25, 0.25, 0.12, 0.15, 0.25] },
  { char: '}', vector: [0.25, 0.15, 0.12, 0.25, 0.25, 0.15] },
  { char: '<', vector: [0.05, 0.25, 0.25, 0.12, 0.05, 0.25] },
  { char: '>', vector: [0.25, 0.05, 0.12, 0.25, 0.25, 0.05] },

  // Special symbols
  { char: '#', vector: [0.58, 0.58, 0.62, 0.62, 0.58, 0.58] },
  { char: '@', vector: [0.62, 0.62, 0.58, 0.58, 0.55, 0.50] },
  { char: '$', vector: [0.48, 0.45, 0.42, 0.45, 0.45, 0.50] },
  { char: '%', vector: [0.48, 0.22, 0.32, 0.32, 0.22, 0.50] },
  { char: '&', vector: [0.40, 0.45, 0.48, 0.35, 0.45, 0.52] },

  // Digits
  { char: '0', vector: [0.45, 0.45, 0.35, 0.35, 0.45, 0.45] },
  { char: '1', vector: [0.18, 0.25, 0.05, 0.25, 0.18, 0.30] },
  { char: '2', vector: [0.35, 0.40, 0.22, 0.35, 0.45, 0.38] },
  { char: '3', vector: [0.32, 0.40, 0.22, 0.35, 0.32, 0.40] },
  { char: '4', vector: [0.35, 0.35, 0.40, 0.35, 0.05, 0.30] },
  { char: '5', vector: [0.45, 0.38, 0.40, 0.32, 0.32, 0.40] },
  { char: '6', vector: [0.28, 0.40, 0.40, 0.35, 0.40, 0.40] },
  { char: '7', vector: [0.40, 0.40, 0.12, 0.28, 0.05, 0.22] },
  { char: '8', vector: [0.45, 0.45, 0.40, 0.40, 0.45, 0.45] },
  { char: '9', vector: [0.40, 0.40, 0.35, 0.40, 0.22, 0.35] },

  // Uppercase letters
  { char: 'A', vector: [0.28, 0.28, 0.50, 0.50, 0.38, 0.38] },
  { char: 'B', vector: [0.50, 0.45, 0.50, 0.40, 0.50, 0.45] },
  { char: 'C', vector: [0.35, 0.40, 0.35, 0.10, 0.35, 0.40] },
  { char: 'D', vector: [0.50, 0.40, 0.45, 0.35, 0.50, 0.40] },
  { char: 'E', vector: [0.45, 0.38, 0.45, 0.28, 0.45, 0.38] },
  { char: 'F', vector: [0.45, 0.38, 0.45, 0.22, 0.32, 0.05] },
  { char: 'G', vector: [0.35, 0.45, 0.35, 0.28, 0.40, 0.45] },
  { char: 'H', vector: [0.38, 0.38, 0.50, 0.50, 0.38, 0.38] },
  { char: 'I', vector: [0.28, 0.28, 0.18, 0.18, 0.28, 0.28] },
  { char: 'J', vector: [0.15, 0.35, 0.05, 0.30, 0.28, 0.35] },
  { char: 'K', vector: [0.38, 0.32, 0.45, 0.28, 0.38, 0.32] },
  { char: 'L', vector: [0.35, 0.00, 0.30, 0.00, 0.45, 0.35] },
  { char: 'M', vector: [0.52, 0.52, 0.45, 0.45, 0.38, 0.38] },
  { char: 'N', vector: [0.45, 0.38, 0.45, 0.45, 0.38, 0.45] },
  { char: 'O', vector: [0.40, 0.40, 0.35, 0.35, 0.40, 0.40] },
  { char: 'P', vector: [0.50, 0.45, 0.45, 0.32, 0.32, 0.00] },
  { char: 'Q', vector: [0.40, 0.40, 0.35, 0.35, 0.40, 0.48] },
  { char: 'R', vector: [0.50, 0.45, 0.45, 0.32, 0.35, 0.28] },
  { char: 'S', vector: [0.32, 0.40, 0.35, 0.32, 0.40, 0.32] },
  { char: 'T', vector: [0.40, 0.40, 0.18, 0.18, 0.12, 0.12] },
  { char: 'U', vector: [0.35, 0.35, 0.35, 0.35, 0.40, 0.40] },
  { char: 'V', vector: [0.38, 0.38, 0.28, 0.28, 0.12, 0.12] },
  { char: 'W', vector: [0.38, 0.38, 0.45, 0.45, 0.52, 0.52] },
  { char: 'X', vector: [0.35, 0.35, 0.28, 0.28, 0.35, 0.35] },
  { char: 'Y', vector: [0.35, 0.35, 0.18, 0.18, 0.12, 0.12] },
  { char: 'Z', vector: [0.40, 0.40, 0.22, 0.22, 0.40, 0.40] },

  // Lowercase letters
  { char: 'a', vector: [0.00, 0.00, 0.28, 0.35, 0.35, 0.40] },
  { char: 'b', vector: [0.32, 0.05, 0.35, 0.30, 0.35, 0.30] },
  { char: 'c', vector: [0.00, 0.00, 0.25, 0.18, 0.25, 0.25] },
  { char: 'd', vector: [0.05, 0.32, 0.30, 0.35, 0.30, 0.35] },
  { char: 'e', vector: [0.00, 0.00, 0.30, 0.30, 0.25, 0.22] },
  { char: 'f', vector: [0.15, 0.28, 0.28, 0.18, 0.22, 0.00] },
  { char: 'g', vector: [0.00, 0.00, 0.30, 0.35, 0.28, 0.40] },
  { char: 'h', vector: [0.28, 0.00, 0.35, 0.28, 0.28, 0.28] },
  { char: 'i', vector: [0.00, 0.12, 0.05, 0.18, 0.05, 0.18] },
  { char: 'j', vector: [0.00, 0.12, 0.00, 0.18, 0.18, 0.22] },
  { char: 'k', vector: [0.28, 0.05, 0.32, 0.22, 0.28, 0.22] },
  { char: 'l', vector: [0.15, 0.12, 0.15, 0.08, 0.12, 0.18] },
  { char: 'm', vector: [0.00, 0.00, 0.40, 0.40, 0.35, 0.35] },
  { char: 'n', vector: [0.00, 0.00, 0.35, 0.28, 0.28, 0.28] },
  { char: 'o', vector: [0.00, 0.00, 0.30, 0.30, 0.30, 0.30] },
  { char: 'p', vector: [0.00, 0.00, 0.35, 0.30, 0.35, 0.12] },
  { char: 'q', vector: [0.00, 0.00, 0.30, 0.35, 0.12, 0.35] },
  { char: 'r', vector: [0.00, 0.00, 0.28, 0.18, 0.18, 0.00] },
  { char: 's', vector: [0.00, 0.00, 0.25, 0.22, 0.22, 0.25] },
  { char: 't', vector: [0.18, 0.12, 0.28, 0.18, 0.12, 0.18] },
  { char: 'u', vector: [0.00, 0.00, 0.28, 0.28, 0.28, 0.35] },
  { char: 'v', vector: [0.00, 0.00, 0.28, 0.28, 0.12, 0.12] },
  { char: 'w', vector: [0.00, 0.00, 0.35, 0.35, 0.42, 0.42] },
  { char: 'x', vector: [0.00, 0.00, 0.28, 0.28, 0.28, 0.28] },
  { char: 'y', vector: [0.00, 0.00, 0.28, 0.28, 0.18, 0.30] },
  { char: 'z', vector: [0.00, 0.00, 0.28, 0.28, 0.28, 0.28] },
];

/**
 * Precomputed 6D shape vectors for block/quadrant characters.
 * These are computed analytically from exact geometric coverage.
 */
export const BLOCK_CHAR_SHAPE_VECTORS: CharacterShapeEntry[] = [
  // Space
  { char: ' ', vector: [0.00, 0.00, 0.00, 0.00, 0.00, 0.00] },
  // Full block
  { char: '█', vector: [1.00, 1.00, 1.00, 1.00, 1.00, 1.00] },
  // Half blocks
  { char: '▀', vector: [1.00, 1.00, 0.55, 0.60, 0.00, 0.00] },
  { char: '▄', vector: [0.00, 0.00, 0.45, 0.40, 1.00, 1.00] },
  { char: '▌', vector: [1.00, 0.00, 1.00, 0.00, 1.00, 0.00] },
  { char: '▐', vector: [0.00, 1.00, 0.00, 1.00, 0.00, 1.00] },
  // Quadrant characters (2×2 sub-cell regions)
  { char: '▘', vector: [1.00, 0.00, 0.55, 0.00, 0.00, 0.00] }, // upper-left
  { char: '▝', vector: [0.00, 1.00, 0.00, 0.60, 0.00, 0.00] }, // upper-right
  { char: '▖', vector: [0.00, 0.00, 0.45, 0.00, 1.00, 0.00] }, // lower-left
  { char: '▗', vector: [0.00, 0.00, 0.00, 0.40, 0.00, 1.00] }, // lower-right
  { char: '▚', vector: [1.00, 0.00, 0.55, 0.40, 0.00, 1.00] }, // upper-left + lower-right (diagonal)
  { char: '▞', vector: [0.00, 1.00, 0.45, 0.60, 1.00, 0.00] }, // upper-right + lower-left (anti-diagonal)
  { char: '▙', vector: [1.00, 0.00, 1.00, 0.40, 1.00, 1.00] }, // all except upper-right
  { char: '▛', vector: [1.00, 1.00, 1.00, 0.60, 1.00, 0.00] }, // all except lower-right
  { char: '▜', vector: [1.00, 1.00, 0.55, 1.00, 0.00, 1.00] }, // all except lower-left
  { char: '▟', vector: [0.00, 1.00, 0.45, 1.00, 1.00, 1.00] }, // all except upper-left
];

// ── Normalization ─────────────────────────────────────────────────────────────

/**
 * Normalize shape vectors so that the max value in each dimension = 1.0.
 * This ensures the full range of characters is utilized during lookups.
 */
export function normalizeShapeVectors(
  entries: CharacterShapeEntry[]
): CharacterShapeEntry[] {
  if (entries.length === 0) return [];

  const dims = entries[0].vector.length;
  const maxPerDim = new Array(dims).fill(0);

  for (const entry of entries) {
    for (let i = 0; i < dims; i++) {
      if (entry.vector[i] > maxPerDim[i]) {
        maxPerDim[i] = entry.vector[i];
      }
    }
  }

  return entries.map(entry => ({
    char: entry.char,
    vector: entry.vector.map((v, i) =>
      maxPerDim[i] > 0 ? v / maxPerDim[i] : 0
    ) as [number, number, number, number, number, number],
  }));
}

// Pre-normalized vectors ready for use (lazily computed from canvas rendering)
let _normalizedAscii: CharacterShapeEntry[] | null = null;
let _normalizedBlocks: CharacterShapeEntry[] | null = null;

/** All 95 printable ASCII characters (0x20–0x7E) */
const PRINTABLE_ASCII = Array.from({ length: 95 }, (_, i) => String.fromCharCode(32 + i));

/** Block + quadrant characters used by block-characters mode */
const BLOCK_CHARACTERS = [
  ' ', '█', '▀', '▄', '▌', '▐',
  '▘', '▝', '▖', '▗', '▚', '▞', '▙', '▛', '▜', '▟',
];

/**
 * Get normalized shape vectors for basic ASCII characters.
 * Generates accurate vectors from the browser's monospace font on first call,
 * falling back to the static estimates if canvas is unavailable.
 */
export function getNormalizedAsciiVectors(): CharacterShapeEntry[] {
  if (!_normalizedAscii) {
    _normalizedAscii = tryGenerateFromCanvas(PRINTABLE_ASCII)
      ?? normalizeShapeVectors(BASIC_ASCII_SHAPE_VECTORS);
  }
  return _normalizedAscii;
}

/**
 * Get normalized shape vectors for block/quadrant characters.
 * Generates accurate vectors from the browser's monospace font on first call,
 * falling back to the static estimates if canvas is unavailable.
 */
export function getNormalizedBlockVectors(): CharacterShapeEntry[] {
  if (!_normalizedBlocks) {
    _normalizedBlocks = tryGenerateFromCanvas(BLOCK_CHARACTERS)
      ?? normalizeShapeVectors(BLOCK_CHAR_SHAPE_VECTORS);
  }
  return _normalizedBlocks;
}

/**
 * Attempt to generate shape vectors by rendering characters on a canvas.
 * Returns null if not running in a browser environment.
 */
function tryGenerateFromCanvas(characters: string[]): CharacterShapeEntry[] | null {
  if (typeof document === 'undefined') return null;
  try {
    return generateShapeVectors(characters);
  } catch {
    return null;
  }
}

// ── Browser-based shape vector generator ──────────────────────────────────────

/**
 * Generate shape vectors by rendering characters on a canvas.
 * This produces exact vectors for the current browser's monospace font.
 * Call this in a browser environment to regenerate or verify the precomputed vectors.
 *
 * @param characters - Array of single characters to compute vectors for
 * @param fontFamily - Monospace font to use (default: 'monospace')
 * @param fontSize - Font size in pixels (default: 48 for precision)
 * @param samplesPerCircle - Number of sample points per sampling circle (default: 64)
 */
export function generateShapeVectors(
  characters: string[],
  fontFamily: string = 'monospace',
  fontSize: number = 48,
  samplesPerCircle: number = 64
): CharacterShapeEntry[] {
  // Cell dimensions for the font (monospace chars are typically ~0.6 width:height)
  const cellWidth = Math.ceil(fontSize * 0.6);
  const cellHeight = fontSize;

  const canvas = document.createElement('canvas');
  canvas.width = cellWidth;
  canvas.height = cellHeight;
  const ctx = canvas.getContext('2d')!;

  const entries: CharacterShapeEntry[] = [];

  for (const char of characters) {
    // Clear canvas (black background)
    ctx.fillStyle = '#000000';
    ctx.fillRect(0, 0, cellWidth, cellHeight);

    // Draw character in white
    ctx.fillStyle = '#FFFFFF';
    ctx.font = `${fontSize}px ${fontFamily}`;
    ctx.textBaseline = 'top';
    ctx.textAlign = 'center';
    ctx.fillText(char, cellWidth / 2, 0);

    const imageData = ctx.getImageData(0, 0, cellWidth, cellHeight);
    const pixels = imageData.data;

    // Sample each of the 6 internal circles
    const vector: [number, number, number, number, number, number] = [0, 0, 0, 0, 0, 0];

    for (let ci = 0; ci < INTERNAL_CIRCLES.length; ci++) {
      const [cx, cy, cr] = INTERNAL_CIRCLES[ci];
      const centerPx = cx * cellWidth;
      const centerPy = cy * cellHeight;
      const radiusPx = cr * Math.min(cellWidth, cellHeight);

      let hits = 0;
      let total = 0;

      // Grid-sample within the circle
      const step = (radiusPx * 2) / Math.sqrt(samplesPerCircle);
      for (let sy = centerPy - radiusPx; sy <= centerPy + radiusPx; sy += step) {
        for (let sx = centerPx - radiusPx; sx <= centerPx + radiusPx; sx += step) {
          const dx = sx - centerPx;
          const dy = sy - centerPy;
          if (dx * dx + dy * dy > radiusPx * radiusPx) continue;

          const px = Math.floor(sx);
          const py = Math.floor(sy);
          if (px < 0 || px >= cellWidth || py < 0 || py >= cellHeight) continue;

          total++;
          const idx = (py * cellWidth + px) * 4;
          // Use red channel (white text = high value)
          if (pixels[idx] > 128) hits++;
        }
      }

      vector[ci] = total > 0 ? hits / total : 0;
    }

    entries.push({ char, vector });
  }

  return normalizeShapeVectors(entries);
}
